swagger: '2.0'
info:
  version: 0.1.0
  title: Netlify API definition
securityDefinitions:
  netlify_auth:
    type: oauth2
    flow: implicit
    authorizationUrl: https://app.netlify.com/authorize
    scopes:
      write:sites: modify sites in your account
      read:sites: read sites in your account
security:
  - netlify_auth:
      - write:sites
      - read:sites
consumes:
  - application/io.swagger.netlify.v1+json
produces:
  - application/io.swagger.netlify.v1+json
schemes:
  - https
basePath: /api/v1
paths:
  /sites:
    get:
      operationId: listSites
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "definitions.yml#/site"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
    post:
      operationId: createSite
      consumes:
        - application/json
      parameters:
        - name: site
          in: body
          schema:
            $ref: "definitions.yml#/site"
          required: true
      responses:
        '201':
          description: Created
          schema:
            $ref: "definitions.yml#/site"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /sites/{site_id}:
    parameters:
      - name: site_id
        type: string
        in: path
        required: true
    get:
      operationId: getSite
      responses:
        '200':
          description: OK
          schema:
            $ref: "definitions.yml#/site"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
    patch:
      operationId: updateSite
      consumes:
        - application/json
      parameters:
        - name: site
          in: body
          schema:
            $ref: "definitions.yml#/site"
          required: true
      responses:
        '204':
          description: Updated
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
    delete:
      operationId: deleteSite
      responses:
        '200':
          description: OK
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /sites/{site_id}/ssl:
    post:
      operationId: provisionSiteSSL
      parameters:
        - name: site_id
          type: string
          in: path
          required: true
      responses:
        '200':
          description: OK
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /sites/{site_id}/forms:
    get:
      operationId: listSiteForms
      parameters:
        - name: site_id
          type: string
          in: path
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "definitions.yml#/form"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /sites/{site_id}/submissions:
    get:
      operationId: listSiteSubmissions
      parameters:
        - name: site_id
          type: string
          in: path
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "definitions.yml#/submission"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /sites/{site_id}/files:
    get:
      operationId: listSiteFiles
      parameters:
        - name: site_id
          type: string
          in: path
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "definitions.yml#/file"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /sites/{site_id}/files/{file_path}:
    get:
      operationId: getSiteFileByPathName
      parameters:
        - name: site_id
          type: string
          in: path
          required: true
        - name: file_path
          type: string
          in: path
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: "definitions.yml#/file"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /sites/{site_id}/snippets:
    parameters:
      - name: site_id
        type: string
        in: path
        required: true
    get:
      operationId: listSiteSnippets
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "definitions.yml#/snippet"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
    post:
      operationId: createSiteSnippet
      consumes:
        - application/json
      parameters:
        - name: snippet
          in: body
          schema:
            $ref: "definitions.yml#/snippet"
          required: true
      responses:
        '201':
          description: OK
          schema:
            $ref: "definitions.yml#/snippet"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /sites/{site_id}/snippets/{snippet_id}:
    parameters:
      - name: site_id
        type: string
        in: path
        required: true
      - name: snippet_id
        type: string
        in: path
        required: true
    get:
      operationId: getSiteSnippet
      responses:
        '200':
          description: OK
          schema:
            $ref: "definitions.yml#/snippet"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
    put:
      operationId: updateSiteSnippet
      consumes:
        - application/json
      parameters:
        - name: snippet
          in: body
          schema:
            $ref: "definitions.yml#/snippet"
          required: true
      responses:
        '204':
          description: No content
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
    delete:
      operationId: deleteSiteSnippet
      responses:
        '204':
          description: No content
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /sites/{site_id}/metadata:
    parameters:
      - name: site_id
        type: string
        in: path
        required: true
    get:
      operationId: getSiteMetadata
      responses:
        '200':
          description: OK
          schema:
            $ref: "definitions.yml#/metadata"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
    put:
      operationId: updateSiteMetadata
      parameters:
        - name: metadata
          in: body
          schema:
            $ref: "definitions.yml#/metadata"
          required: true
      responses:
        '204':
          description: No content
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /sites/{site_id}/deploys:
    get:
      operationId: listSiteDeploys
      parameters:
        - name: site_id
          type: string
          in: path
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "definitions.yml#/deploy"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /sites/{site_id}/deploys/{deploy_id}:
    get:
      operationId: getSiteDeploy
      parameters:
        - name: site_id
          type: string
          in: path
          required: true
        - name: deploy_id
          type: string
          in: path
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: "definitions.yml#/deploy"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /sites/{site_id}/deploys/{deploy_id}/restore:
    post:
      operationId: restoreSiteDeploy
      parameters:
        - name: site_id
          type: string
          in: path
          required: true
        - name: deploy_id
          type: string
          in: path
          required: true
      responses:
        '201':
          description: Created
          schema:
            $ref: "definitions.yml#/deploy"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /forms:
    get:
      operationId: listForms
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "definitions.yml#/form"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /forms/{form_id}/submissions:
    get:
      operationId: listFormSubmissions
      parameters:
        - name: form_id
          type: string
          in: path
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "definitions.yml#/submission"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /hooks:
    get:
      operationId: listHooksBySiteId
      parameters:
        - name: site_id
          in: query
          type: string
          required: true
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "definitions.yml#/hook"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
    post:
      operationId: createHookBySiteId
      consumes:
        - application/json
      parameters:
        - name: hook
          in: body
          schema:
            $ref: "definitions.yml#/hook"
          required: true
      responses:
        '201':
          description: OK
          schema:
            $ref: "definitions.yml#/hook"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
  /hooks/{hook_id}:
    delete:
      operationId: deleteHookBySiteId
      parameters:
        - name: hook_id
          type: string
          in: path
          required: true
      responses:
        '204':
          description: No content
  /hooks/types:
    get:
      operationId: listHookTypes
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: "definitions.yml#/hookType"
        default:
          description: error
          schema:
            $ref: "definitions.yml#/error"
